"""initial schema

Revision ID: 56eeb72c2be3
Revises:
Create Date: 2026-03-29 15:11:48.220169

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '56eeb72c2be3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('window', sa.String(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('win_accuracy', sa.Float(), nullable=True),
    sa.Column('top3_accuracy', sa.Float(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('ndcg', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('records_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('race_number', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('track_condition', sa.String(), nullable=True),
    sa.Column('weather', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('track_temperature', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'race_date', 'race_number', name='uq_race_identity')
    )
    op.create_index('ix_races_date', 'races', ['race_date'], unique=False)
    op.create_table('riders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_kana', sa.String(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('home_track_id', sa.Integer(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['home_track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('odds_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('ticket_type', sa.String(), nullable=False),
    sa.Column('combination', sa.String(), nullable=False),
    sa.Column('odds_value', sa.Float(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_odds_race_type', 'odds_snapshot', ['race_id', 'ticket_type'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('ticket_type', sa.String(), nullable=False),
    sa.Column('combination', sa.String(), nullable=False),
    sa.Column('predicted_prob', sa.Float(), nullable=False),
    sa.Column('odds_at_prediction', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('kelly_fraction', sa.Float(), nullable=True),
    sa.Column('recommended_bet', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('post_position', sa.Integer(), nullable=False),
    sa.Column('handicap_meters', sa.Integer(), nullable=False),
    sa.Column('trial_time', sa.Float(), nullable=True),
    sa.Column('avg_trial_time', sa.Float(), nullable=True),
    sa.Column('trial_deviation', sa.Float(), nullable=True),
    sa.Column('race_score', sa.Float(), nullable=True),
    sa.Column('entry_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'post_position', name='uq_entry_position')
    )
    op.create_index('ix_race_entries_rider', 'race_entries', ['rider_id'], unique=False)
    op.create_table('betting_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('actual_bet_amount', sa.Float(), nullable=False),
    sa.Column('payout', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('bankroll_after', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.create_table('race_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_entry_id', sa.Integer(), nullable=False),
    sa.Column('finish_position', sa.Integer(), nullable=True),
    sa.Column('race_time', sa.Float(), nullable=True),
    sa.Column('start_timing', sa.Float(), nullable=True),
    sa.Column('accident_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['race_entry_id'], ['race_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_results')
    op.drop_table('betting_log')
    op.drop_index('ix_race_entries_rider', table_name='race_entries')
    op.drop_table('race_entries')
    op.drop_table('predictions')
    op.drop_index('ix_odds_race_type', table_name='odds_snapshot')
    op.drop_table('odds_snapshot')
    op.drop_table('riders')
    op.drop_index('ix_races_date', table_name='races')
    op.drop_table('races')
    op.drop_table('tracks')
    op.drop_table('scrape_log')
    op.drop_table('model_performance')
    # ### end Alembic commands ###
