"""add keiba tables

Revision ID: 9d42e2a442e0
Revises: b4f8e2a1c7d3
Create Date: 2026-04-05 08:32:13.320365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d42e2a442e0'
down_revision: Union[str, Sequence[str], None] = 'b4f8e2a1c7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keiba_horses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blood_registration_number', sa.String(length=8), nullable=False),
    sa.Column('horse_name', sa.String(), nullable=True),
    sa.Column('sex_code', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.String(length=8), nullable=True),
    sa.Column('sire_name', sa.String(), nullable=True),
    sa.Column('dam_name', sa.String(), nullable=True),
    sa.Column('broodmare_sire_name', sa.String(), nullable=True),
    sa.Column('sire_code', sa.String(length=4), nullable=True),
    sa.Column('broodmare_sire_code', sa.String(length=4), nullable=True),
    sa.Column('retired_flag', sa.Integer(), nullable=True),
    sa.Column('sire_id', sa.Integer(), nullable=True),
    sa.Column('dam_id', sa.Integer(), nullable=True),
    sa.Column('broodmare_sire_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['broodmare_sire_id'], ['keiba_horses.id'], ),
    sa.ForeignKeyConstraint(['dam_id'], ['keiba_horses.id'], ),
    sa.ForeignKeyConstraint(['sire_id'], ['keiba_horses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blood_registration_number')
    )
    op.create_table('keiba_import_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name', name='uq_keiba_import_log_file')
    )
    op.create_table('keiba_jockeys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jockey_code', sa.String(length=5), nullable=False),
    sa.Column('jockey_name', sa.String(), nullable=True),
    sa.Column('affiliation_code', sa.Integer(), nullable=True),
    sa.Column('apprentice_class', sa.Integer(), nullable=True),
    sa.Column('retired_flag', sa.Integer(), nullable=True),
    sa.Column('career_flat_1st', sa.Integer(), nullable=True),
    sa.Column('career_flat_2nd', sa.Integer(), nullable=True),
    sa.Column('career_flat_3rd', sa.Integer(), nullable=True),
    sa.Column('career_flat_unplaced', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jockey_code')
    )
    op.create_table('keiba_racecourses',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keiba_trainers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trainer_code', sa.String(length=5), nullable=False),
    sa.Column('trainer_name', sa.String(), nullable=True),
    sa.Column('affiliation_code', sa.Integer(), nullable=True),
    sa.Column('retired_flag', sa.Integer(), nullable=True),
    sa.Column('career_flat_1st', sa.Integer(), nullable=True),
    sa.Column('career_flat_2nd', sa.Integer(), nullable=True),
    sa.Column('career_flat_3rd', sa.Integer(), nullable=True),
    sa.Column('career_flat_unplaced', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainer_code')
    )
    op.create_table('keiba_races',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_key', sa.String(length=8), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('racecourse_id', sa.Integer(), nullable=True),
    sa.Column('race_number', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('surface_code', sa.Integer(), nullable=True),
    sa.Column('direction_code', sa.Integer(), nullable=True),
    sa.Column('course_type_code', sa.Integer(), nullable=True),
    sa.Column('going_code', sa.Integer(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('race_name', sa.String(), nullable=True),
    sa.Column('class_code', sa.String(), nullable=True),
    sa.Column('weight_rule_code', sa.String(), nullable=True),
    sa.Column('num_runners', sa.Integer(), nullable=True),
    sa.Column('post_time', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['racecourse_id'], ['keiba_racecourses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_key', name='uq_keiba_races_key')
    )
    op.create_index('ix_keiba_races_date', 'keiba_races', ['race_date'], unique=False)
    op.create_table('keiba_race_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('post_position', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=True),
    sa.Column('jockey_id', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('blood_registration_number', sa.String(length=8), nullable=True),
    sa.Column('jockey_code', sa.String(length=5), nullable=True),
    sa.Column('trainer_code', sa.String(length=5), nullable=True),
    sa.Column('impost_weight', sa.Float(), nullable=True),
    sa.Column('base_win_odds', sa.Float(), nullable=True),
    sa.Column('idm', sa.Float(), nullable=True),
    sa.Column('jockey_index', sa.Float(), nullable=True),
    sa.Column('info_index', sa.Float(), nullable=True),
    sa.Column('training_index', sa.Float(), nullable=True),
    sa.Column('stable_index', sa.Float(), nullable=True),
    sa.Column('composite_index', sa.Float(), nullable=True),
    sa.Column('running_style_code', sa.Integer(), nullable=True),
    sa.Column('distance_aptitude_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['keiba_horses.id'], ),
    sa.ForeignKeyConstraint(['jockey_id'], ['keiba_jockeys.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['keiba_races.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['keiba_trainers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'post_position', name='uq_keiba_entry_identity')
    )
    op.create_table('keiba_ticket_payouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('ticket_type', sa.String(), nullable=False),
    sa.Column('combination', sa.String(), nullable=False),
    sa.Column('payout_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['keiba_races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'ticket_type', 'combination', name='uq_keiba_payout_identity')
    )
    op.create_table('keiba_race_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('finish_position', sa.Integer(), nullable=True),
    sa.Column('race_time', sa.Float(), nullable=True),
    sa.Column('last_3f_time', sa.Float(), nullable=True),
    sa.Column('first_3f_time', sa.Float(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('corner_1_pos', sa.Integer(), nullable=True),
    sa.Column('corner_2_pos', sa.Integer(), nullable=True),
    sa.Column('corner_3_pos', sa.Integer(), nullable=True),
    sa.Column('corner_4_pos', sa.Integer(), nullable=True),
    sa.Column('confirmed_win_odds', sa.Float(), nullable=True),
    sa.Column('confirmed_popularity', sa.Integer(), nullable=True),
    sa.Column('jrdb_speed_figure', sa.Float(), nullable=True),
    sa.Column('body_weight', sa.Integer(), nullable=True),
    sa.Column('body_weight_change', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['keiba_race_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id')
    )
    op.drop_index(op.f('ix_races_telvote_close'), table_name='races')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_races_telvote_close'), 'races', ['telvote_close_at'], unique=False)
    op.drop_table('keiba_race_results')
    op.drop_table('keiba_ticket_payouts')
    op.drop_table('keiba_race_entries')
    op.drop_index('ix_keiba_races_date', table_name='keiba_races')
    op.drop_table('keiba_races')
    op.drop_table('keiba_trainers')
    op.drop_table('keiba_racecourses')
    op.drop_table('keiba_jockeys')
    op.drop_table('keiba_import_log')
    op.drop_table('keiba_horses')
    # ### end Alembic commands ###
